[tool.poetry]
name = "kalc"
version = "0.1.1"
description = "Kalc - the Kubernetes Calculator core"
authors = ["CriticalHop Team <info@criticalhop.com>"]
license = "Apache-2.0"
readme = "README.md"

packages = [
    { include = "kalc" },
]

[tool.poetry.dependencies]
python = ">=3.7"
PyYAML = "^5.1.2"
yaspin = "^0.15.0"
Click = "^7.0"
logzero = "^1.5.0"
# pyupdater = "^3.1"
poodle = ">=0.1.1"
pandas = "^0.25.3"
Pygments = "^2.5"
jsonpatch = "^1.24"
setuptools = "^45.0.0"

[tool.poetry.scripts]
kalc-optimize = "kalc.misc.cli_optimize:optimize_cluster"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

