[tool.poetry]
name = "django-edelweiss-data-usermanager"
version = "0.0.2"
description = "User management django application for Edelweiss Data"
license = "MIT"
authors = ["Edelweiss Connect <info@edelweissconnect.com>"]
readme = "README.md"
packages = [
  { include = "django_edelweiss_data" }
]
exclude = ["django_edelweiss_data/**/*"]
include = ["django_edelweiss_data/usermanager/**/*"]

[tool.poetry.dependencies]
python = "^3.6"
Django = "^2.2, ^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
